/**
 * firestore.rules — AUDIT TRAIL and the SERVER-ONLY collections
 *
 * Covers the collections that exist to make the money workflows trustworthy:
 *   - auditLogs      — append-only trail (NN-12)
 *   - adjustments    — ledger adjustments, server-authoritative (v1.1)
 *   - dailySummaries — generated by the scheduled function only
 *
 * ⚠️ This file contains a CHARACTERIZATION test that pins a KNOWN-OPEN defect
 * (AUDIT SECURITY H-3 / NN-12 violation: `auditLogs` create does not verify
 * `userId == request.auth.uid`). It asserts the CURRENT permissive behaviour so
 * the gap is visible and tracked — NOT because forgeable audit entries are
 * acceptable. When H-3 is fixed, that single test must be flipped to
 * `assertFails`; it is written to fail loudly at that moment, by design.
 */

import { beforeAll, afterAll, beforeEach, describe, it } from 'vitest';
import { assertFails, assertSucceeds, type RulesTestEnvironment } from '@firebase/rules-unit-testing';
import { doc, getDoc, setDoc, updateDoc, deleteDoc } from 'firebase/firestore';
import { UIDS, NOW, as, asAnonymous, getTestEnv, resetWithUsers, seed, teardown } from './helpers';

let env: RulesTestEnvironment;

beforeAll(async () => { env = await getTestEnv(); });
afterAll(async () => { await teardown(); });
beforeEach(async () => { await resetWithUsers(env); });

const auditEntry = (overrides: Record<string, unknown> = {}) => ({
  userId: UIDS.accounts,
  action: 'APPROVE',
  entity: 'Bill',
  entityId: 'bill_1',
  timestamp: NOW,
  details: 'Approved bill BILL-001',
  ...overrides,
});

describe('auditLogs — append-only', () => {
  it('ALLOWS an authenticated user to append an entry', async () => {
    await assertSucceeds(
      setDoc(doc(as(env, 'accounts'), 'auditLogs', 'log_1'), auditEntry()),
    );
  });

  it('DENIES an unauthenticated caller appending an entry', async () => {
    await assertFails(
      setDoc(doc(asAnonymous(env), 'auditLogs', 'log_anon'), auditEntry()),
    );
  });

  it('DENIES updating an existing entry (immutability)', async () => {
    await seed(env, [{ path: ['auditLogs', 'log_1'], data: auditEntry() }]);
    await assertFails(
      updateDoc(doc(as(env, 'admin'), 'auditLogs', 'log_1'), { details: 'rewritten' }),
    );
  });

  it('DENIES deleting an entry, even as ADMIN (immutability)', async () => {
    await seed(env, [{ path: ['auditLogs', 'log_1'], data: auditEntry() }]);
    await assertFails(deleteDoc(doc(as(env, 'admin'), 'auditLogs', 'log_1')));
  });

  it('ALLOWS ADMIN to read the audit trail', async () => {
    await seed(env, [{ path: ['auditLogs', 'log_1'], data: auditEntry() }]);
    await assertSucceeds(getDoc(doc(as(env, 'admin'), 'auditLogs', 'log_1')));
  });

  it('ALLOWS CEO to read the audit trail', async () => {
    await seed(env, [{ path: ['auditLogs', 'log_1'], data: auditEntry() }]);
    await assertSucceeds(getDoc(doc(as(env, 'ceo'), 'auditLogs', 'log_1')));
  });

  it('DENIES a PM reading the audit trail', async () => {
    await seed(env, [{ path: ['auditLogs', 'log_1'], data: auditEntry() }]);
    await assertFails(getDoc(doc(as(env, 'pm'), 'auditLogs', 'log_1')));
  });

  it('DENIES ACCOUNTS reading the audit trail', async () => {
    await seed(env, [{ path: ['auditLogs', 'log_1'], data: auditEntry() }]);
    await assertFails(getDoc(doc(as(env, 'accounts'), 'auditLogs', 'log_1')));
  });

  // ---------------------------------------------------------------
  // KNOWN-OPEN DEFECT — AUDIT SECURITY H-3, violates NN-12.
  // `allow create: if isAuthenticated()` does not bind userId to auth.uid,
  // so any signed-in user can author an entry attributed to someone else.
  // Tracked, NOT accepted. Fix = add
  //   && request.resource.data.userId == request.auth.uid
  // then flip this assertion to assertFails.
  // ---------------------------------------------------------------
  it('CHARACTERIZATION (KNOWN GAP H-3): a forged userId is currently ALLOWED', async () => {
    await assertSucceeds(
      setDoc(doc(as(env, 'pm'), 'auditLogs', 'log_forged'), auditEntry({
        userId: UIDS.ceo,          // ← not the caller
        action: 'APPROVE',
        details: 'Attributed to the CEO but written by a PM',
      })),
    );
  });
});

describe('adjustments — server-authoritative ledger writes', () => {
  it('DENIES ACCOUNTS creating an adjustment from the client', async () => {
    await assertFails(setDoc(doc(as(env, 'accounts'), 'adjustments', 'adj_1'), {
      contractorId: 'contractor_1',
      amount: 25_000,
      type: 'DEBIT',
      category: 'PENALTY',
      description: 'Delay penalty',
      date: NOW,
      createdAt: NOW,
      createdBy: UIDS.accounts,
    }));
  });

  it('DENIES ADMIN creating an adjustment from the client', async () => {
    await assertFails(setDoc(doc(as(env, 'admin'), 'adjustments', 'adj_2'), {
      contractorId: 'contractor_1', amount: 1, type: 'CREDIT',
      category: 'BONUS', description: 'x', date: NOW, createdAt: NOW, createdBy: UIDS.admin,
    }));
  });

  it('DENIES updating an existing adjustment from the client', async () => {
    await seed(env, [{ path: ['adjustments', 'adj_3'], data: {
      contractorId: 'contractor_1', amount: 1, type: 'DEBIT',
      category: 'OTHER', description: 'x', date: NOW, createdAt: NOW, createdBy: UIDS.admin,
    } }]);
    await assertFails(updateDoc(doc(as(env, 'admin'), 'adjustments', 'adj_3'), { amount: 999 }));
  });

  it('ALLOWS any authenticated user to read adjustments', async () => {
    await seed(env, [{ path: ['adjustments', 'adj_4'], data: {
      contractorId: 'contractor_1', amount: 1, type: 'DEBIT',
      category: 'OTHER', description: 'x', date: NOW, createdAt: NOW, createdBy: UIDS.admin,
    } }]);
    await assertSucceeds(getDoc(doc(as(env, 'accounts'), 'adjustments', 'adj_4')));
  });
});

describe('dailySummaries — written only by the scheduled function', () => {
  const summary = {
    date: NOW,
    totalOutstanding: 100,
    payable7Days: 10,
    overdueAmount: 5,
    topRiskItems: [],
    formattedText: 'summary',
    createdAt: NOW,
  };

  it('DENIES ADMIN creating a daily summary from the client', async () => {
    await assertFails(setDoc(doc(as(env, 'admin'), 'dailySummaries', 'sum_1'), summary));
  });

  it('DENIES CEO creating a daily summary from the client', async () => {
    await assertFails(setDoc(doc(as(env, 'ceo'), 'dailySummaries', 'sum_2'), summary));
  });

  it('ALLOWS CEO to read a daily summary', async () => {
    await seed(env, [{ path: ['dailySummaries', 'sum_3'], data: summary }]);
    await assertSucceeds(getDoc(doc(as(env, 'ceo'), 'dailySummaries', 'sum_3')));
  });

  it('DENIES a PM reading a daily summary', async () => {
    await seed(env, [{ path: ['dailySummaries', 'sum_4'], data: summary }]);
    await assertFails(getDoc(doc(as(env, 'pm'), 'dailySummaries', 'sum_4')));
  });
});

describe('users — role and status self-escalation', () => {
  it('DENIES a PM promoting themselves to ADMIN', async () => {
    await assertFails(updateDoc(doc(as(env, 'pm'), 'users', UIDS.pm), { role: 'ADMIN' }));
  });

  it('DENIES a PM activating their own PENDING status', async () => {
    await seed(env, [{ path: ['users', UIDS.outsider], data: {
      uid: UIDS.outsider, email: 'outsider@dsbc.test', displayName: 'o',
      role: 'PROJECT_MANAGER', status: 'PENDING', createdAt: NOW,
    } }]);
    await assertFails(
      updateDoc(doc(as(env, 'outsider'), 'users', UIDS.outsider), { status: 'ACTIVE' }),
    );
  });

  it('ALLOWS a PM to edit their own non-privileged profile fields', async () => {
    await assertSucceeds(
      updateDoc(doc(as(env, 'pm'), 'users', UIDS.pm), { displayName: 'New Name' }),
    );
  });

  it('ALLOWS an ADMIN to change another user role', async () => {
    await assertSucceeds(
      updateDoc(doc(as(env, 'admin'), 'users', UIDS.pm), { role: 'ACCOUNTS' }),
    );
  });

  it('DENIES an ADMIN changing their OWN role (another admin must do it)', async () => {
    await assertFails(
      updateDoc(doc(as(env, 'admin'), 'users', UIDS.admin), { role: 'SUPER_ADMIN' }),
    );
  });

  it('DENIES deleting a real uid-keyed user document', async () => {
    await assertFails(deleteDoc(doc(as(env, 'admin'), 'users', UIDS.pm)));
  });
});
